radio_app/api/urls.py
from django.urls import path
from radio_app.api.views import registeration_view
from radio_app.api.views import scheduleview
from radio_app.api.views import login_view,subscribed_user_check
from radio_app.api.views import profileview,update_rj_request,show_rj_request,single_request,approve_rj,delete_rj_request,delete_subscribe
from rest_framework_jwt.views import obtain_jwt_token
from radio_app.api.views import current_user,server_view,all_schedule,single_schedule,update_rj
from radio_app.api.views import all_users,show_schedule,update_schedule,ip_track,delete_schedule,delete_schedule_account
from radio_app.api.views import user_track,add_comment,show_comment,show_image,add_subscribed_user,profile_list_view,profile_update

# from radio_app.api.views import Registration_view
# from radio_app.api.serializer import UserSerializer
app_name='radio_app'

urlpatterns=[
    path('token-auth', obtain_jwt_token),
    path('current_user/<int:id>', current_user),
    path('users',all_users,name='users'),
    path('register',registeration_view,name='register'),
    path('view_schedule',scheduleview,name ='schedule'),
    path('show_schedule/<int:id>',show_schedule,name ='show'),
    path('update_schedule/<int:id>',update_schedule,name ='update'),
    path('login',login_view,name='login'),
    path('profile/<int:id>/',profileview,name='profile'),
    path('userTrack',user_track,name="usertrack"),
    path('comments/<int:id>',add_comment,name="comment"),
    path('image/',show_image,name="image"),
    path('show_comment/<int:id>',show_comment,name="listcomment"),
    path('subscribed_user/',add_subscribed_user,name="subscription"),
    path('profile_list/',profile_list_view,name="profile_list"),
    path('ip_track/',ip_track,name="track_ip"),
    path('profile_update/<int:id>',profile_update,name='profile_update'),
    path('delete_schedule/<int:id>',delete_schedule,name='delete'),
    path('delete_schedule_account/<int:id>',delete_schedule_account,name='delete_schedule'),
    path('server',server_view,name='server'),
    path('all_schedule',all_schedule,name='all'),
    path('single_schedule/<int:id>',single_schedule,name='single'),
    path('update_rj/<int:id>',update_rj,name='rj'),
    path('update_rj_request/<int:id>',update_rj_request,name='rj_request'),
    path("show_rj_request",show_rj_request,name="request_list"),
    path('single_request/<int:id>',single_request,name='single_request'),
    path('approve_rj/<int:id>',approve_rj,name='approve'),
    path('delete_rj_request/<int:id>',delete_rj_request,name='request_delete'),
    path('sub_check/<int:id>/<int:id1>',subscribed_user_check,name='sub'),
    path('delete_subscribe/<int:id>/<int:id1>',delete_subscribe,name='del_sub'),





]

radion/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static 
from radio_app.views import (home,register,stationsignup,schedulesview,aboutview,schedule_edit,update_schedule,login_view)
urlpatterns = [
    path('logout/',auth_views.LogoutView.as_view(template_name='radio_app/logout.html'),name='logout'),
    path('admin/', admin.site.urls),
    path('home/',home,name='home'),
    path('signup/',register,name='signup'),
    path('signin/',login_view,name='login'),
    path('schedule/',schedulesview,name='article'),
    path('about/',aboutview,name='about'),
    path('account/api/',include('radio_app.api.urls')),
    # path('login/',auth_views.LoginView.as_view(templates=))
    path('station_signup/',stationsignup,name='stationsignup'),
    path('schedule_edit/',schedule_edit,name='schedule_edit'),
    path('update_schedule/<int:id>',update_schedule,name='update_schedule'),

    # path('own/',own_schedule_edit,name='own_schedule_edit'),
]
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

radio_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings

# Create your models here.
class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')
		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


class Account(AbstractBaseUser):
	email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 				= models.CharField(max_length=30, unique=True)
	date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin				= models.BooleanField(default=False)
	is_active				= models.BooleanField(default=True)
	is_staff				= models.BooleanField(default=False)
	is_superuser			= models.BooleanField(default=False)
	is_station              = models.CharField(max_length=255)
	is_normal               = models.BooleanField(default=False)
	is_rj                   = models.BooleanField(default=False)
	owner_id                = models.CharField(max_length=30,null=True,blank=True)
	image                   = models.ImageField(default='jpt.png',upload_to='images/',null=True,blank=True)
	livelink                = models.CharField(max_length=100)
	rj_id                   = models.CharField(max_length=255,null=True,blank=True)

	
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return str(self.id)

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True


class Profile(models.Model):
	user = models.OneToOneField(Account,on_delete=models.CASCADE)
	image = models.ImageField(default='default.png',upload_to='images/')
	# /livelink=models.
	counter = models.CharField(max_length=255,blank= True, null=True)
	livelink=models.CharField(max_length=255)
	trending = models.CharField(max_length=255,default=0)
	def __str__(self):
		return str(self.user.id)
# class Rjprofile(models.Model):
# 	title = models.CharField(max_length=100)
# 	# image = models.ImageField(default='jpt.png',upload_to='images/',null=True,blank=True)
# 	datetime_field_start = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
# 	datetime_field_end = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
# 	# timefield = models.TimeField(verbose_name='date joined',auto_now_add=False)
# 	owner = models.ForeignKey(Profile,on_delete=models.CASCADE)
# 	rj = models.ManyToManyField(Account,blank= True, null=True)
# 	def __str__(self):
# 		return str(self.rj)

class Schedule(models.Model):
	title = models.CharField(max_length=100)
	# image = models.ImageField(default='jpt.png',upload_to='images/',null=True,blank=True)
	datetime_field_start = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
	datetime_field_end = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
	# timefield = models.TimeField(verbose_name='date joined',auto_now_add=False)
	owner = models.ForeignKey(Profile,on_delete=models.CASCADE)
	rj = models.ManyToManyField(Account,blank= True, null=True)
	requested = models.BooleanField(default=False)
	# image = models.ManyToManyField(Image)
	def __str__(self):
		return str(self.rj)
class Rjrequest(models.Model):
	title=models.CharField(max_length=255)
	datetime_field_start = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
	datetime_field_end = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
	owner = models.ForeignKey(Profile,on_delete=models.CASCADE)
	image = models.ImageField(default='jpt.png',upload_to='images/',null=True,blank=True)
	rj = models.ForeignKey(Account,on_delete=models.CASCADE)
	
class IpAddress(models.Model):
	ip= models.CharField(max_length=255)
	location = models.CharField(max_length=255)
	listen_date = models.DateTimeField(auto_now_add=False,blank=True,null=True)
	station = models.ForeignKey(Profile,on_delete=models.CASCADE)
class UserTrack(models.Model):
	start_datefield =  models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
	end_datefield = models.DateTimeField(verbose_name='date joined',auto_now_add=False,blank=True,null=True)
class Images(models.Model):
		rjs = models.ForeignKey(Account,null=True,blank=True,on_delete=models.CASCADE)
		schedule = models.ForeignKey(Schedule, default=None,on_delete=models.CASCADE)
		image = models.ImageField(default='jpt.png',upload_to='images/',null=True,blank=True)
	
from django.db import models 
class Subscribe(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    account = models.ForeignKey(Account,on_delete=models.CASCADE)
    
class Pizza(models.Model):

    name = models.CharField(max_length=30)
    toppings = models.ManyToManyField('Topping')

    def __str__(self):
        return self.name


class Topping(models.Model):

    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Comment(models.Model):
	profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
	account = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	content = models.TextField(max_length=160)
	schedule_id = models.IntegerField(null=True,blank=True)
	reply = models.ForeignKey('Comment',null=True,related_name="replies",on_delete=models.CASCADE)
	timestamp = models.DateTimeField(auto_now_add=True)
	def  __str__(self):
		return '{}'.format(str(self.account.username))
	    

radio_app/forms.py
from radio_app.models import Schedule
from django import forms
from django.contrib.auth.forms import UserCreationForm
from radio_app.models import Account
from django.contrib.auth import login, authenticate, logout
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker

class ScheduleForm(forms.ModelForm):
    datetime_field = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )
    class Meta:
        model = Schedule
        fields = ['title','datetime_field','owner','rj']

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2')
    def	save(self):
            account = Account(
                        email=self.cleaned_data['email'],
                        username=self.cleaned_data['username']
                    )
            password = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password != password2:
                return 'did not matched'
            account.set_password(password)
            account.is_station=True
            
            account.save()
            return account
class AuthenticationForm(forms.ModelForm):
    class Meta:
        model = Account
        fields=['email','password']
    def clean(self):
	    if self.is_valid():
		    email = self.cleaned_data['email']
		    password = self.cleaned_data['password']
		    if not authenticate(email=email, password=password):
			    raise forms.ValidationError("Invalid login")

    

radio_app/views.py
from django.db.models import Q
from django.shortcuts import render,redirect
from radio_app.forms import ScheduleForm
from radio_app.models import Schedule
from radio_app.models import Account
from radio_app.forms import RegistrationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from radio_app.docorators import station_login_required 
from radio_app.forms import AuthenticationForm
import simplejson as json
# Create your views here.
def home(request):
    return render(request,'index.html')

def register(request):
    return render(request,'signup.html')
def login_view(request):
    # user = request.user
    context={}
    # if user.is_authenticated:
    #     return redirect('home')
    if request.method=='POST':
        form = AuthenticationForm(request.POST)
        print(form)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email,password=password)
            if user:
                login(request,user)
                return redirect('home')
        else:
            print('errror')
    form = AuthenticationForm()
    context['form']=form
    return render(request,'radio_app/authenticate.html',context)
def stationsignup(request):
	context = {}
	if request.POST:
            form = RegistrationForm(request.POST)
            if form.is_valid():
                
                form.save()
                email = form.cleaned_data.get('email')
                raw_password = form.cleaned_data.get('password1')
                account = authenticate(email=email, password=raw_password)
                login(request, account)
                return redirect('/login')
            else:
                context['registration_form'] = form

	else:
		form = RegistrationForm()
		context['registration_form'] = form
	return render(request, 'radio_app/station_signup.html', context)


# def stationsignup(request):
    
#     return render(request,'radio_app/station_signup.html')
def schedulesview(request):
        # context = {}
    if request.POST:
        form = ScheduleForm(request.POST,request.FILES)
        print(form)
        if form.is_valid():
            id = form.cleaned_data['rj']
            img = form.cleaned_data['image']
            owns = form.cleaned_data['owner']
            title = form.cleaned_data['title']
            date = form.cleaned_data['datetime_field']
            print(id)
            print(title,date,img)
            form.save()
            # acc = Account.objects.filter(schedule__id=6)
    # taking value form schedule from which is connected to two table account and profile and using that value to update the account column value

            for i in id:
                print(i)
                i.is_rj=True
                i.rj_id=str(i)
                i.owner_id = str(owns)
                i.save()
            # acc = Account.objects.filter(schedule__id=1).first()
            # acc.is_rj=True
            # acc.save()
            # acc = Account.objects.filter(schedule__id=1)
            return redirect('about')
        
    else:
        form = ScheduleForm()
        print(form)
        # context['registration_form'] = form
    
    return render(request, 'radio_app/article.html', {'form':form})
def aboutview(request):
    return render(request,'radio_app/about.html')
@login_required
@station_login_required
def schedule_edit(request):
    
    user_id = request.user.id
    acc = Account.objects.get(id = user_id)
    print(str(acc))
    # she=Schedule.objects.
    owner = acc.rj_id
    sch_owner=acc.owner_id
    
    if owner==sch_owner:
        schedule =Schedule.objects.filter(Q(rj=owner) | Q(owner_id=sch_owner))
    else:
        schedule =Schedule.objects.filter(rj=owner)
    print('this schedule is {}'.format(schedule))
    context = {'schedules':schedule}
    print('the schedule is is{}'.format(schedule[0].id))
    return render(request,'radio_app/about.html',context)
@login_required
@station_login_required
def update_schedule(request,id):
    context={}
    id = str(id)
    schedule = get_object_or_404(Schedule, id = id)
    print(schedule)
    if request.method=='POST':
        form = ScheduleForm(request.POST,request.FILES,instance=schedule)
        print(form)
        if form.is_valid():
            title = form.cleaned_data['title']
            rj = form.cleaned_data['datetime_field']
            image = form.cleaned_data['image']

            print(title,rj,image)
            
            obj = form.save()
            
            schedule=obj
            context['success_message']="successfully updated"
        else:
            print("not valid")
    else:
        print("error")
        form = ScheduleForm(
			initial={
					"title": schedule.title, 
                    "image":schedule.image,
                    "date":schedule.datetime_field,
					"owner": schedule.owner,
                    "rj":   Account.objects.all(),
				}
			)
        print(form)
        # response[datetime_field] = response[datetime_field].strftime("%Y-%m-%d %H:%M:%S")
        context['form'] = form
        context['data'] = json.dumps(str(schedule.datetime_field))
    # context['form'] = schedule
    # context['acc'] = Account.objects.all()
    return render(request,'radio_app/edit_schedule.html',context)

    

radio_app/templates/radio_app/about.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% for schedule in schedules %}
        <h1>{{schedule.title}}</h1>
    
        <a href="{% url 'update_schedule' schedule.id %}">edit</a>
    {% endfor %}
</body>
</html>

radio_app/templates/radio_app/article.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style type="text/css">
        .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
        }
      
        .form-signin .form-control {
          position: relative;
          box-sizing: border-box;
          height: auto;
          padding: 10px;
          font-size: 16px;
        }
        .form-signin .form-control:focus {
          z-index: 2;
        }
        .form-signin input[type="email"] {
          margin-bottom: 10px;
          border-bottom-right-radius: 0;
          border-bottom-left-radius: 0;
        }
        .form-signin input[type="text"] {
          margin-bottom: 10px;
          border-bottom-right-radius: 0;
          border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
          margin-bottom: -1px;
          border-top-left-radius: 0;
          border-top-right-radius: 0;
        }
      
        .h3{
          text-align: center;
        }
      
      </style>
      
      
      
    <title>Document</title>
    
      {# Include FontAwesome; required for icon display #}
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
  
      {# Include Bootstrap 4 and jQuery #}
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  
      {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
      {{ form.media }}
    
  
</head>
<body>
    <form class="form-signin" method="post" enctype="multipart/form-data">{% csrf_token %}
        
        <h1 class="h3 mb-3 font-weight-normal">article</h1>
      {{ form }}
        <!-- <input type="text" name="text" class="form-control" placeholder="title">
        <input type="text" name="text1" class="form-control" placeholder="title1"> -->
        <!-- <select name="cars" multiple>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            
        </select> -->
        
        
      
        <button class="btn btn-lg btn-primary btn-block" type="submit">add</button>
      
      </form>
      
</body>
</html> 

radio_app/templates/radio_app/authenticate.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
    }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
  .h3  {
    text-align: center;
  }
</style>


<form class="form-signin" method="post">{% csrf_token %}
  <div class="d-flex flex-column pb-3">
    <img class="img-fluid mx-auto d-block" src="{% static 'codingwithmitch_logo.png' %}" alt="Codignwithmitch logo image" width="72" height="72">
  </div>
  
  <h1 class="h3 mb-3 font-weight-normal">Login</h1>

  <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  
  <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

  {% for field in login_form %}
      <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  {% if login_form.non_field_errors %}
    <div style="color: red">
      <p>{{login_form.non_field_errors}}</p>
    </div>
      
  {% endif %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>

</form>




{% endblock content %}

radio_app/templates/radio_app/edit_schedule.html
{% extends 'index.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>
 {# Include FontAwesome; required for icon display #}
 <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

 {# Include Bootstrap 4 and jQuery #}
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

 {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
 {{ form.media }}
<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
            
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
                
				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>
				<div class="form-group">
					<label for="id_image">Image</label>
					<input type="file" id="id_image" name='image'>
				</div>
				<label for="id_datetime_field">Datetime field:</label>{{data}}
					<div class="input-group" id="div_id_datetime_field" data-target-input="nearest">
				  <input type="text" name="datetime_field"  id="id_datetime_field" class="form-control  datetimepicker-input" data-toggle="datetimepicker" data-target="#id_datetime_field">
				  
					<div class="input-group-append" data-target="#id_datetime_field" data-toggle="datetimepicker">
						<div class="input-group-text"><i class="fa fa-calendar"></i></div>
						
					</div>
				  <div>
				  
					<script type="text/javascript">
					    
						function deferDateTimePicker_id_datetime_field() {
							// var date = new Date()

							
							// var dates = JSON.parse(datas);
							// console.log(date);
							if (window.jQuery && $.fn.datetimepicker) {
							
								$('#id_datetime_field').datetimepicker({"format": "YYYY-MM-DD HH:mm:ss", "icons": {"time": "fa fa-clock-o"},  "collapse": false});
							} else {
								setTimeout(function() { deferDateTimePicker_id_datetime_field() }, 50);
							}
						}
					
						deferDateTimePicker_id_datetime_field();
					</script>
				<!-- Body -->
				<div class="form-group">
					<label for="id_title">Owner</label>
					<input class="form-control" type="text" name="owner" id="id_title" placeholder="owner" value="{{form.initial.owner}}" required autofocus>
                </div> 
                
				<!-- {% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %} -->

				<!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
                
            </form>	
            
		</div>
	</div>
</div>

{% endblock content %}

radio_app/templates/radio_app/logout.html
{% extends 'index.html' %}
{% block content %}
<h1>login again!!!!!!!!</h1>
{% endblock content %}

radio_app/templates/radio_app/schedule.html
{% extends 'index.html' %}
{% load static %}

{% block content %}


{% endblock content %}

radio_app/templates/radio_app/station_signup.html
{% extends 'index.html' %}
{% load static %}

{% block content %}


<style type="text/css">
  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
  }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="text"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  .h3{
    text-align: center;
  }

</style>


<form class="form-signin" method="post">{% csrf_token %}
  <div class="d-flex flex-column pb-3">
    <img class="img-fluid mx-auto d-block" src="" alt="Codignwithmitch logo image" width="72" height="72">
  </div>
  <h1 class="h3 mb-3 font-weight-normal">Register an account</h1>

  <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

  <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>
  
  <input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

  <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>

  {% for field in registration_form %}
      <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  {% if registration_form.non_field_errors %}
    <div style="color: red">
      <p>{{registration_form.non_field_errors}}</p>
    </div>
      
  {% endif %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

</form>


{% endblock content %}